namespace SpriteKind {
    export const toast = SpriteKind.create()
    export const arrow = SpriteKind.create()
    export const text = SpriteKind.create()
    export const trigger = SpriteKind.create()
    export const trigger2 = SpriteKind.create()
    export const retry = SpriteKind.create()
    export const trigger3 = SpriteKind.create()
    export const box = SpriteKind.create()
    export const speechy = SpriteKind.create()
    export const eville = SpriteKind.create()
}
scene.setBackgroundImage(assets.image`vdssd`)
music.play(music.createSong(assets.song`vfvf`), music.PlaybackMode.UntilDone)
music.play(music.createSong(assets.song`gws`), music.PlaybackMode.UntilDone)
music.play(music.createSong(assets.song`wadw`), music.PlaybackMode.UntilDone)
